[package]
name = "graphics_3d_from_scratch_pikuma"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37", features = ["bundled"] }
native-dialog = "0.7.0"
image = "0.25.6" # Use the latest version
fixed = "1.29"
